/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import APIS.Usuario;
import APIS.UsuarioCliente;
import java.io.IOException;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Laura
 */
    public class GestionUsuarios extends javax.swing.JFrame {
         private UsuarioCliente cliente;
        /**
         * Creates new form GestionUsuarios
         */
        public GestionUsuarios() {
        initComponents();
        this.cliente = new UsuarioCliente();
        cargarUsuarios();

        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setResizable(true);
        setLocationRelativeTo(null);

        getContentPane().setLayout(new java.awt.BorderLayout());
        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(600, 0));
        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        javax.swing.JPanel panelBotones = new javax.swing.JPanel(new java.awt.GridBagLayout());
        panelBotones.setOpaque(false);

        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.insets = new java.awt.Insets(10, 10, 10, 10);
        gbc.gridy = 0;

        if (txtID == null) {
            txtID = new javax.swing.JTextField();
        }
        txtID.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
        txtID.setPreferredSize(new java.awt.Dimension(300, 40));
        gbc.gridx = 0;
        gbc.weightx = 1.0;
        gbc.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panelBotones.add(txtID, gbc);

        gbc.gridx = 1;
        gbc.weightx = 0.0;
        gbc.fill = java.awt.GridBagConstraints.NONE;
        panelBotones.add(btnBuscar, gbc);

        java.awt.Dimension tamBotonInicial = new java.awt.Dimension(160, 48);
        javax.swing.JButton[] botones = { btnEditar, btnEliminar, btnTodos, btnTodos1 };
        int col = 2;
        for (javax.swing.JButton b : botones) {
            b.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 16));
            b.setPreferredSize(tamBotonInicial);
            b.setBackground(new java.awt.Color(70, 130, 180));
            b.setForeground(java.awt.Color.WHITE);
            b.setFocusPainted(false);

            gbc.gridx = col++;
            gbc.weightx = 0.0;
            gbc.fill = java.awt.GridBagConstraints.NONE;
            panelBotones.add(b, gbc);
        }

        jPanel1.add(panelBotones, java.awt.BorderLayout.SOUTH);

        addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                ajustarEscala();
            }
        });

        jPanel1.revalidate();
        jPanel1.repaint();
    }

    // === MÉTODO DE ESCALADO AUTOMÁTICO ===
    private void ajustarEscala() {
        int anchoVentana = Math.max(800, getWidth());
        int altoVentana = Math.max(600, getHeight());

        int altoBoton = Math.max(38, altoVentana / 18);
        int anchoBoton = Math.max(120, anchoVentana / 10);
        int anchoTxt = Math.max(240, anchoVentana / 4);

        java.awt.Dimension tamBoton = new java.awt.Dimension(anchoBoton, altoBoton);
        java.awt.Dimension tamTxt = new java.awt.Dimension(anchoTxt, altoBoton);

        javax.swing.JButton[] botones = { btnBuscar, btnEditar, btnEliminar, btnTodos, btnTodos1 };
        for (javax.swing.JButton b : botones) {
            if (b != null) b.setPreferredSize(tamBoton);
        }

        if (txtID != null) {
            txtID.setPreferredSize(tamTxt);
        }

        jPanel1.revalidate();
        jPanel1.repaint();
    }
    public void cargarUsuarios(){
        try{
            List<Usuario> usuarios = cliente.listarTodosUsuarios();
            DefaultTableModel model=new DefaultTableModel();
            model.setColumnIdentifiers(new Object[]{"Id","nombre","email","contraseña"});
            for(Usuario u: usuarios){
                model.addRow(new Object[]{u.getId(),u.getNombre(),u.getCorreoElectronico(),u.getContrasena()});
            }
            tblUsuarios.setModel(model);
            tblUsuarios.revalidate();
            tblUsuarios.repaint();
        }catch(IOException e){
            JOptionPane.showMessageDialog(this,"error al cargar usuarios");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnTodos = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        btnTodos1 = new javax.swing.JButton();

        jButton4.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblUsuarios);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 6, 398, 275));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 6, 34, -1));

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 140, 99, 36));

        btnTodos.setText("Todos");
        btnTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodosActionPerformed(evt);
            }
        });
        jPanel1.add(btnTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 188, 99, 36));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 92, 99, 36));
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 15, 97, -1));

        btnTodos1.setText("Regresar");
        btnTodos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodos1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnTodos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 236, 99, 36));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
     try{
          int fila = tblUsuarios.getSelectedRow();
    if (fila == -1) {
      JOptionPane.showMessageDialog(this,"fila no seleccionada,seleccione fila para eliminar");
    }

    int id = (int) tblUsuarios.getValueAt(fila, 0);

    cliente.eliminarUsuario(id);
    JOptionPane.showMessageDialog(this, "usuario eliminado.");
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String texto=txtID.getText();
        if(!texto.isEmpty()){
            try{
               int id=Integer.parseInt(texto);
               Usuario usuario=cliente.buscarUsuarioPorId(id);
               DefaultTableModel model1=new DefaultTableModel();
               model1.setColumnIdentifiers(new String[]{"Id","nombre","email","contraseña"});
               
               if(usuario!=null){
               model1.addRow(new Object[]{usuario.getId(),usuario.getNombre(),usuario.getCorreoElectronico(),usuario.getContrasena()});
               
               
               }else{
                   JOptionPane.showMessageDialog(this,"usuario no encontrado");
               }
               tblUsuarios.setModel(model1);
            }catch(IOException e){
                JOptionPane.showMessageDialog(this, e);
            }
        }
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        
         int fila = tblUsuarios.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this,"fila no seleccionada");
        }

       
        
        String correoElectronico=(String) tblUsuarios.getValueAt(fila, 2);
        String contrasena=(String) tblUsuarios.getValueAt(fila, 3);
        String nombre=(String) tblUsuarios.getValueAt(fila, 1);
        int id = (int) tblUsuarios.getValueAt(fila, 0);
        String rol=(String) tblUsuarios.getValueAt(fila,4);
        Usuario usuario=new Usuario(correoElectronico, contrasena, nombre, id, rol);
       

  
            Editar ventanaR = new Editar(usuario, this);
            ventanaR.setVisible(true);
            dispose();
        
    
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodosActionPerformed
        // TODO add your handling code here:
      cargarUsuarios();
        
    }//GEN-LAST:event_btnTodosActionPerformed

    private void btnTodos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodos1ActionPerformed
        // TODO add your handling code here:
        VeantanaGestion VG = new VeantanaGestion();
        VG.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnTodos1ActionPerformed

    /**
     * @param args the command line arguments
     */
      

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnTodos;
    private javax.swing.JButton btnTodos1;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
